language: ruby
bundler_args: --without development
rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.0
env:
  - DB=sqlite
services:
  - redis-server
before_script:
  - cp config/database.example.yml config/database.yml
  - cp config/secrets.example.yml config/secrets.yml
script: RAILS_ENV=test bundle exec rake test
