language: ruby
bundler_args: --without development production mysql2 postgres
rvm:
  - 2.2.0
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql
services:
  - redis-server
before_script:
  - cp config/database.$DB.yml config/database.yml
  - cp config/secrets.example.yml config/secrets.yml
  - RAILS_ENV=test bundle exec rake db:setup
script: CODECLIMATE_REPO_TOKEN=1632e8154ae461cb75f2af554bd962764d220ad8d305f971b64b6e79a5726902 RAILS_ENV=test bundle exec rake test
